# Generated by Django 4.1.2 on 2022-11-07 21:50

from django.db import migrations
from PetClinicAPI.apps.authentication.models import User

def popule_user_admin(apps, schema_editor):
    user = User.objects.create(
        first_name='Admin',
        last_name='Admin',
        email='admin@admin.com',
        role=User.RoleChoices.ADMIN,
        password='123123',
    )

    user.set_password('123123')
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popule_user_admin),
    ]
