# Generated by Django 4.1.2 on 2022-11-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20221107_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('veterinary', 'Veterinary'), ('admin', 'Admin'), ('operator', 'Operator')], default='operator', max_length=255),
        ),
    ]
