# Generated by Django 4.1.2 on 2022-11-04 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('drugs', models.ManyToManyField(blank=True, null=True, to='clinic.drug', verbose_name='Remédios')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.pet', verbose_name='Paciente')),
                ('veterinary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.veterinary', verbose_name='Veterinário')),
            ],
        ),
    ]
