# Generated by Django 4.1.2 on 2022-11-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='drugs',
            field=models.ManyToManyField(to='clinic.drug', verbose_name='Remédios'),
        ),
    ]
