# Generated by Django 4.1.2 on 2022-11-08 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_appointment_drugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='veterinary',
        ),
    ]
