# Generated by Django 4.1.2 on 2022-11-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_avaliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliation', to='clinic.appointment', verbose_name='Consulta'),
        ),
    ]
